# .checkov.yml

# Frameworks à scanner
framework:
  - terraform

# Format de sortie
output:
  - cli

# Options générales
quiet: true
compact: true
download-external-modules: true
evaluate-variables: true

# Répertoires à scanner
directory:
  - .

skip-check:
  - CKV_TF_1    # Ensure Terraform module sources use a commit hash
  - CKV_AWS_130 # Public subnets assign public IP by design
  - CKV_AWS_338 # Example uses short log retention for demo purposes

# Répertoires à exclure
skip-path:
  - .terraform/
  - .terragrunt-cache/
  - "**/.terraform/"
  - "**/.terraform.lock.hcl"
  - "**/.terragrunt-cache/"
  - "**/terraform"
  - "**/terraform-output.json"
  - "*.tfstate*"
  - "**/*.tfstate*"
  - terraform-output.json
